package com.version1.recognition.nomination.comms;

/**
 * A message generated by a coordinator decision.
 * <p>
 * There is no mail server wired up, so nothing leaves the building - this is the
 * exact text that <em>would</em> be sent, captured so the audit log can show a
 * coordinator what the nominator was told, word for word, months later.
 * <p>
 * Recording the rendered text rather than re-rendering it on demand is
 * deliberate: templates get reworded, and a record that quietly changes to match
 * today's template is not a record of anything.
 */
public class SentEmail {

    private final String recipient;
    private final String subject;
    private final String body;

    public SentEmail(String recipient, String subject, String body) {
        this.recipient = recipient;
        this.subject = subject;
        this.body = body;
    }

    public String getRecipient() {
        return recipient;
    }

    public String getSubject() {
        return subject;
    }

    public String getBody() {
        return body;
    }
}
