package com.version1.recognition.nomination.model;

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import java.time.Instant;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

/**
 * One message generated by a decision, stored against the audit entry that
 * caused it.
 * <p>
 * A decision can produce more than one: approving sends the nominator a
 * confirmation and the nominee the award itself. That is why this is a
 * collection rather than a set of columns on the audit row - the first version
 * had room for exactly one message and quietly dropped the nominee's.
 * <p>
 * The text is stored as it was written. Templates get reworded, and a record
 * that changes to match today's wording is not a record.
 */
@Embeddable
public class SentComm {

    public enum Recipient {
        /** The person who submitted the nomination. */
        NOMINATOR,
        /** The person being recognised. */
        NOMINEE
    }

    @Column(name = "recipient_email", nullable = false)
    private String recipientEmail;

    @Enumerated(EnumType.STRING)
    @Column(name = "recipient_role", nullable = false, length = 20)
    private Recipient recipientRole;

    @Column(name = "subject", length = 500)
    private String subject;

    @JdbcTypeCode(SqlTypes.LONGVARCHAR)
    @Column(name = "body")
    private String body;

    @Column(name = "sent_at", nullable = false)
    private Instant sentAt;

    protected SentComm() {
        // required by JPA
    }

    public SentComm(String recipientEmail, Recipient recipientRole, String subject, String body) {
        this.recipientEmail = recipientEmail;
        this.recipientRole = recipientRole;
        this.subject = subject;
        this.body = body;
        this.sentAt = Instant.now();
    }

    public String getRecipientEmail() {
        return recipientEmail;
    }

    public Recipient getRecipientRole() {
        return recipientRole;
    }

    public String getSubject() {
        return subject;
    }

    public String getBody() {
        return body;
    }

    public Instant getSentAt() {
        return sentAt;
    }
}
